name: Start EC2

on:
#  schedule:
#    - cron: '45 23 * * *'   # 台灣 07:45
#    - cron: '45 10 * * *'   # 台灣 18:45
  workflow_dispatch:

jobs:
  start-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Start EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            # #AWS_SESSION_TOKEN : ${{ secrets.#AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ap-northeast-1
        run: |
          INSTANCE_ID="i-0b9fe2660a50a202f"
          echo "🟢 Starting EC2..."
          aws ec2 start-instances --instance-ids $INSTANCE_ID
